# vi: ft=yaml
---
- name: Install and set up PHP7.0
  hosts: servers
  remote_user: root

  tasks:
    - block:
        - name: PHP7 | Ensure php stuff is installed
          apt:
            name: "{{ item }}"
            state: present
            update_cache: yes
          with_items:
            - php7.0-cli
            - php7.0-common
            - php7.0-fpm
            - php7.0-json
            - php7.0-opcache
            - php7.0-readline
            - php7.0-mbstring
            - php7.0-gd
      rescue:
        - name: PHP7 | Revert php install
          apt: 
            name: "{{ item }}"
            state: absent 
          with_items:
            - php7.0-cli
            - php7.0-common
            - php7.0-fpm
            - php7.0-json
            - php7.0-opcache
            - php7.0-readline
            - php7.0-mbstring
            - php7.0-gd
